const coinImages: Record<string, string> = {
  bitcoin: "bitcoin.png",
  ethereum: "ethereum.png",
  tether: "tether.png",
  cardano: "cardano.png",
  polkadot: "polkadot.png",
  solana: "solana.png",
  polygon: "polygon.png",
  dogecoin: "dogecoin.png",
  litecoin: "litecoin.png",
  tron: "tron.png",
  xrp: "xrp.png",
  avalanche: "avalanche.png",
  stellar: "stellar.png",
  chainlink: "chainlink.png",
  "binance-usd": "binanceusd.png",
  trueusd: "trueusd.png",
  uniswap: "uniswap.png",
  monero: "monero.png",
  okb: "okb.png",
  "ethereum-classic": "ethereumclassic.png",
  cosmos: "cosmos.png",
  "internet-computer": "Internetcomputer.png",
  filecoin: "filecoin.png",
  "lido-dao": "Lidodao.png",
  "multi-collateral-dai": "dai.png",
  "wrapped-bitcoin": "wrappedbitcoin.png",
  "bitcoin-cash": "bitcoincash.png",
  "usd-coin": "usdcoin.png",
  "binance-coin": "binancecoin.png",
  "shiba-inu": "shibainu.png",
  "unus-sed-leo": "leo.png",
  "bitcoin-bep2": "bitcoin.png",
};

export default coinImages;
